# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go mod download
    - ./completions.sh
release:
  github:
    owner: Files-com
    name: files-cli
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
    ignore:
      - goos: windows
        goarch: arm
    main: ./main.go
    binary: files-cli
archives:
  # default format for Mac (darwin) and Linux
  - format: tar.gz
    # if the OS is windows, we override and put everything in a .zip instead.
    format_overrides:
      - goos: windows
        format: zip
    # Just the naming convention for tarballs... Example: msconsole_1.0.0_darwin_64bit
    name_template: '{{.ProjectName}}_{{.Os}}_{{.Arch}}{{.Arm}}'
    # Replace the cryptic arch's with readable human naming conventions
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - CHANGELOG.md
      - completions/*
changelog:
  sort: asc
  use: github
  groups:
    - title: 'New Features'
      regexp: '^### Add'
      order: 100
    - title: 'Bug Fixes'
      regexp: '^### Fix'
      order: 200
    - title: 'Bug Fixes'
      regexp: '^### Fix'
      order: 200
    - title: 'Improvements'
      regexp: '^### Improvement'
      order: 300
    - title: 'Change'
      regexp: '^### Change'
      order: 400
    - title: 'Documentation Change'
      regexp: '^### Documentation Change'
      order: 500
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
brews:
  -
    name: files-cli
    tap:
      owner: Files-com
      name: homebrew-tap
    commit_author:
      name: files-opensource-bot
      email: info@files.com
    folder: Formula
    homepage: "https://files.com/"
    description: Files.com command-line interface
    license: "MIT"
    test: system "#{bin}/files-cli --version"
    install: |-
      bin.install "files-cli"
      bash_completion.install "completions/files-cli.bash" => "files-cli"
      zsh_completion.install "completions/files-cli.zsh" => "_files-cli"
      fish_completion.install "completions/files-cli.fish"
nfpms:
  -
    package_name: files-cli
    vendor: Files.com
    homepage: https://files.com/
    description: Files.com command-line interface
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
    file_name_template: '{{.ProjectName}}_{{.Os}}_{{.Arch}}{{.Arm}}'
    maintainer: 'Dustin Zeisler <dustin.zeisler@files.com>'
    contents:
      - src: ./completions/files-cli.bash
        dst: /usr/share/bash-completion/completions/files-cli
        file_info:
          mode: 0644
      - src: ./completions/files-cli.fish
        dst: /usr/share/fish/vendor_completions.d/files-cli.fish
        file_info:
          mode: 0644
      - src: ./completions/files-cli.zsh
        dst: /usr/share/zsh/vendor-completions/_files-cli
        file_info:
          mode: 0644
signs:
  - artifacts: checksum
#dockers:
#  -
#    use: podman
#    image_templates:
#      - "gcr.io/files-com/files-cli:{{ .Tag }}"
#      - "gcr.io/files-com/files-cli:latest"
