# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
release:
  github:
    owner: Files-com
    name: files-cli
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
    ignore:
      - goos: windows
        goarch: arm
    main: ./main.go
    binary: files-cli
archives:
  # default format for Mac (darwin) and Linux
  - format: tar.gz
    # if the OS is windows, we override and put everything in a .zip instead.
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}_{{if eq .Os "darwin"}}macOS{{else}}{{.Os}}{{end}}_{{if eq .Arch "amd64"}}64bit{{else}}{{.Arch}}{{end}}{{.Arm}}'
    files:
      - README.md
      - completions/*
changelog:
  sort: asc
  use: git
  abbrev: -1
  filters:
    exclude:
      - '^.*$'  # Exclude all by default
    include:
      - '^\s*- .*'  # Include lines that start with optional whitespace followed by '- '
      - '^#.*'  # Include lines that start with '#'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
brews:
  -
    name: files-cli
    repository:
      owner: Files-com
      name: homebrew-tap
    commit_author:
      name: files-opensource-bot
      email: info@files.com
    folder: Formula
    homepage: "https://files.com/"
    description: Files.com command-line interface
    license: "MIT"
    test: system "#{bin}/files-cli --version"
    install: |-
      @last_version = JSON.parse(`brew info files-cli --json`, symbolize_names: true).first[:linked_keg] rescue nil
      bin.install "files-cli"
      bash_completion.install "completions/files-cli.bash" => "files-cli"
      zsh_completion.install "completions/files-cli.zsh" => "_files-cli"
      fish_completion.install "completions/files-cli.fish"
    post_install: |
      puts `#{bin}/files-cli changelog #{@last_version ? @last_version + '...' : ''}"$(#{bin}/files-cli -v)" --ignore-version-check`
nfpms:
  -
    package_name: files-cli
    vendor: Files.com
    homepage: https://files.com/
    description: Files.com command-line interface
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
    file_name_template: '{{.ProjectName}}_{{.Os}}_{{.Arch}}{{.Arm}}'
    maintainer: 'Dustin Zeisler <dustin.zeisler@files.com>'
    contents:
      - src: ./completions/files-cli.bash
        dst: /usr/share/bash-completion/completions/files-cli
        file_info:
          mode: 0644
      - src: ./completions/files-cli.fish
        dst: /usr/share/fish/vendor_completions.d/files-cli.fish
        file_info:
          mode: 0644
      - src: ./completions/files-cli.zsh
        dst: /usr/share/zsh/vendor-completions/_files-cli
        file_info:
          mode: 0644
signs:
  - artifacts: checksum
