# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
release:
  github:
    owner: Files-com
    name: files-cli
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
    ignore:
      - goos: windows
        goarch: arm
    main: ./main.go
    binary: files-cli
archives:
  # default format for Mac (darwin) and Linux
  - format: tar.gz
    # if the OS is windows, we override and put everything in a .zip instead.
    format_overrides:
      - goos: windows
        format: zip
    # Just the naming convention for tarballs... Example: msconsole_1.0.0_darwin_64bit
    name_template: '{{.ProjectName}}_{{.Os}}_{{.Arch}}{{.Arm}}'
    # Replace the cryptic arch's with readable human naming conventions
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
brews:
  -
    name: files-cli
    tap:
      owner: Files-com
      name: homebrew-tap
    commit_author:
      name: files-opensource-bot
      email: info@files.com
    folder: Formula
    homepage: "https://files.com/"
    description: Files.com command-line interface
    license: "MIT"
    test: system "#{bin}/files-cli --version"
nfpms:
  -
    package_name: files-cli
    vendor: Files.com
    homepage: https://files.com/
    description: Files.com command-line interface
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
    file_name_template: '{{.ProjectName}}_{{.Os}}_{{.Arch}}{{.Arm}}'
    maintainer: 'Dustin Zeisler <dustin.zeisler@files.com>'
